main: net.ebiggz.biggzadditions.BiggzAdditions
name: BiggzAdditions
version: 1.0.0
load: POSTWORLD
api-version: 1.16
author: ebiggz
description: General purpose plugin.
depend: [Vault, Herochat, PlayerParticles, Residence]
permissions:
  affixer.colors:
    default: true
  affixer.colornames:
    default: true
  affixer.prefix:
    default: true
  affixer.suffix:
    default: true
  affixer.*:
    default: op
    children:
      affixer.colornames: true
      affixer.colors: true
      affixer.prefix: true
      affixer.suffix: true
  booty.nickname.self:
    default: false
  booty.nickname.others:
    default: false
  booty.*:
    default: op
    children:
      booty.nickname.self: true
      booty.nickname.others: true
  booty.admin:
    default: op